workflows:
  ios-release:
    name: iOS Release Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: POA App Store Connect
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: de.poa-platform.ios
      node: 20
      xcode: latest
      cocoapods: default
      vars:
        APP_NAME: "POA"
        BUNDLE_ID: "de.poa-platform.ios"
    triggering:
      events:
        - tag
      tag_patterns:
        - pattern: 'ios-v*'
          include: true
      branch_patterns:
        - pattern: main
          include: true
    scripts:
      - name: Install Node.js dependencies
        script: |
          cd apps/ios-wrapper
          npm install

      - name: Sync Capacitor iOS project
        script: |
          cd apps/ios-wrapper
          npx cap sync ios

      - name: Copy app icon
        script: |
          cd apps/ios-wrapper
          cp resources/AppIcon-1024.png ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-512@2x.png

      - name: Install CocoaPods dependencies
        script: |
          cd apps/ios-wrapper/ios/App
          pod install

      - name: Set up code signing
        script: |
          xcode-project use-profiles

      - name: Increment build number
        script: |
          cd apps/ios-wrapper/ios/App
          LATEST_BUILD_NUMBER=$(app-store-connect get-latest-testflight-build-number "$BUNDLE_ID" || echo 0)
          agvtool new-version -all $(($LATEST_BUILD_NUMBER + 1))

      - name: Build iOS app
        script: |
          cd apps/ios-wrapper/ios/App
          xcode-project build-ipa \
            --workspace App.xcworkspace \
            --scheme App

    artifacts:
      - apps/ios-wrapper/ios/App/build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - apps/ios-wrapper/ios/App/*.dSYM.zip

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        expire_build_submitted_for_review: true
      email:
        recipients:
          - info@poa-platform.de
        notify:
          success: true
          failure: true

  ios-dev:
    name: iOS Development Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: POA App Store Connect
    environment:
      ios_signing:
        distribution_type: development
        bundle_identifier: de.poa-platform.ios
      node: 20
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'ios/*'
          include: true
    scripts:
      - name: Install Node.js dependencies
        script: |
          cd apps/ios-wrapper
          npm install

      - name: Sync Capacitor iOS project
        script: |
          cd apps/ios-wrapper
          npx cap sync ios

      - name: Copy app icon
        script: |
          cd apps/ios-wrapper
          cp resources/AppIcon-1024.png ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-512@2x.png

      - name: Install CocoaPods dependencies
        script: |
          cd apps/ios-wrapper/ios/App
          pod install

      - name: Set up code signing
        script: |
          xcode-project use-profiles

      - name: Build iOS app
        script: |
          cd apps/ios-wrapper/ios/App
          xcode-project build-ipa \
            --workspace App.xcworkspace \
            --scheme App

    artifacts:
      - apps/ios-wrapper/ios/App/build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
